export default {
  "Food & Drink": {
    Cuisine: [
      "Indian",
      "Greek",
      "Thai",
      "Seafood",
      "Himalayan/Nepalese",
      "Ramen",
      "Sushi Bars",
      "Chinese",
      "Vietnamese",
      "Mexican",
      "American",
      "Italian",
      "Japanese",
      "Korean",
      "Barbeque",
      "French",
      "Mediterranean",
      "Pakistani",
      "Peruvian",
      "Hawaiian",
      "Moroccan",
      "New American",
      "British",
      "Southern",
      "Burmese",
      "Malaysian",
      "Mongolian",
      "Turkish",
      "German",
      "Halal",
    ],
    "Specialty Foods & Desserts": [
      "Seafood Markets",
      "Ice Cream & Frozen Yogurt",
      "Gelato",
      "Desserts",
      "Juice Bars & Smoothies",
      "Shaved Ice",
      "Poke",
      "Gluten-Free",
      "Live/Raw Food",
      "Fruits & Veggies",
    ],
    "Bars & Nightlife": [
      "Cocktail Bars",
      "Brewpubs",
      "Wine Bars",
      "Bars",
      "Beer Bars",
      "Beer Gardens",
      "Dive Bars",
      "Whiskey Bars",
      "Sports Bars",
      "Lounges",
      "Pubs",
      "Tapas Bars",
      "Gastropubs",
      "Karaoke",
      "Music Venues",
      "Nightlife",
    ],
  },
  "Recreation & Outdoors": {
    "Outdoor Activities": [
      "Hiking",
      "Horseback Riding",
      "Mountain Biking",
      "Beaches",
      "Parks",
      "Playgrounds",
      "Dog Parks",
      "Campgrounds",
      "RV Parks",
      "Scuba Diving",
      "Tennis",
    ],
    "Sports & Fitness": [
      "Bikes",
      "Sports Wear",
      "Outdoor Gear",
      "Amateur Sports Teams",
      "Recreation Centers",
      "Sports Medicine",
    ],
  },
  "Shopping & Services": {
    "Retail & Specialty Stores": [
      "Grocery",
      "Seafood Markets",
      "Asian Fusion",
      "Gift Shops",
      "Bookstores",
      "Used Bookstore",
      "Nurseries & Gardening",
      "International Grocery",
    ],
    "Personal & Home Services": [
      "Laundry Services",
      "Laundromat",
      "Car Wash",
      "Caterers",
      "Party & Event Planning",
      "Venues & Event Spaces",
      "Gas Stations",
      "Convenience Stores",
      "Recycling Center",
      "Auto Repair",
      "Auto Parts & Supplies",
    ],
  },
  "Travel & Hospitality": {
    Accommodations: ["Hotels", "Resorts", "Bed & Breakfast"],
    "Tours & Landmarks": [
      "Landmarks & Historical Buildings",
      "Tours",
      "Boat Charters",
    ],
  },
  "Health & Wellness": {
    "Healthcare Services": [
      "Family Practice",
      "Counseling & Mental Health",
      "Podiatrists",
      "Orthopedists",
      "Physical Therapy",
      "Veterinarians",
      "Sports Medicine",
    ],
    "Fitness & Activities": [
      "Recreation Centers",
      "Tennis",
      "Hiking",
      "Mountain Biking",
    ],
  },
  "Entertainment & Events": {
    "Leisure Activities": [
      "Kids Activities",
      "Playgrounds",
      "Dog Parks",
      "Karaoke",
      "Music Venues",
      "Cinema",
      "Nightlife",
      "Yelp Events",
    ],
  },
};
